seed: 2005
lineup: ['SS','2B','CF','1B','DH','RF','LF','3B','C']
batters:
  C:  {BA: 0.239, OBP: 0.307}
  1B: {BA: 0.249, OBP: 0.324}
  2B: {BA: 0.242, OBP: 0.311}
  3B: {BA: 0.245, OBP: 0.317}
  SS: {BA: 0.257, OBP: 0.321}
  LF: {BA: 0.248, OBP: 0.321}
  CF: {BA: 0.250, OBP: 0.320}
  RF: {BA: 0.255, OBP: 0.324}
  DH: {BA: 0.252, OBP: 0.330}
hit_distribution:
  single: 0.69
  double: 0.21
  triple: 0.02
  home_run: 0.08
steal_att_1b_to_2b: 0.02
steal_att_2b_to_3b: 0.006
steal_succ_1b_to_2b: 0.74
steal_succ_2b_to_3b: 0.70
walk_hbp_bump: 0.003
